# Copyright 2025-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

[workspace]
resolver = "2"
members = [
  "crates/*",
]
exclude = [
  "crates/.claude",
]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
homepage = "https://github.com/DataDog/serverless-components"
repository = "https://github.com/DataDog/serverless-components"

[workspace.dependencies]
libdd-common = { version = "5.2.0", default-features = false }
libdd-trace-obfuscation = { version = "6.0.0", default-features = false }
libdd-trace-utils = { version = "10.1.0", default-features = false }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
