/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function hello(): string
/** JavaScript-compatible service status */
export interface JsServiceStatus {
  /** Status name: "starting", "running", "stopping", "stopped" */
  status: string
}
/** JavaScript-compatible configuration object */
export interface JsServicesConfig {
  /** Datadog API key for authentication */
  apiKey?: string
  /** DogStatsD server port (default: 8125) */
  dogstatsdPort?: number
  /** Datadog site (default: datadoghq.com) */
  site?: string
  /** Whether to enable DogStatsD (default: true) */
  useDogstatsd?: boolean
  /** Optional metric namespace prefix */
  metricNamespace?: string
  /** HTTPS proxy URL */
  httpsProxy?: string
  /** Log level: trace, debug, info, warn, error (default: info) */
  logLevel?: string
}
/** Main class for controlling Datadog serverless services from Node.js */
export declare class DatadogServices {
  /** Create a new DatadogServices instance */
  constructor()
  /** Start the Datadog services */
  start(config: JsServicesConfig, statusCallback?: (status: JsServiceStatus) => void): void
  /** Stop the Datadog services */
  stop(): void
  /** Check if services are running */
  isRunning(): boolean
  /** Register cleanup hook to automatically stop services on process exit */
  registerCleanupHook(): void
}
