name: Build Datadog Serverless Compat

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

jobs:
  setup:
    name: Setup
    runs-on: ${{ inputs.runner }}
    env:
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4 # v1.11.0
        with:
          cache: false
      - uses: mozilla-actions/sccache-action@65101d47ea8028ed0c98a1cdea8dd9182e9b5133 #v0.0.8
  build-datadog-serverless-compat:
    name: Build Datadog Serverless Compat
    if: ${{ inputs.runner != 'ubuntu-24.04-arm' }}
    needs: setup
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Protoc Binary
        shell: bash
        run: chmod +x ./scripts/install-protoc.sh && ./scripts/install-protoc.sh $HOME
      - if: ${{ inputs.runner == 'ubuntu-24.04' }}
        shell: bash
        run: |
          sudo apt-get update
          rustup target add x86_64-unknown-linux-musl && sudo apt-get install -y musl-tools
          cargo build --release -p datadog-serverless-compat --target x86_64-unknown-linux-musl
      - if: ${{ inputs.runner == 'ubuntu-24.04' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # 4.6.2
        with:
          name: linux-amd64
          path: target/x86_64-unknown-linux-musl/release/datadog-serverless-compat
          retention-days: 3
      - if: ${{ inputs.runner == 'windows-2022' }}
        shell: bash
        run: cargo build --release -p datadog-serverless-compat
      - if: ${{ inputs.runner == 'windows-2022' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # 4.6.2
        with:
          name: windows-amd64
          path: target/release/datadog-serverless-compat.exe
          retention-days: 3
