name: Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cargo:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm, windows-2022]
    uses: ./.github/workflows/cargo.yml
    with:
      runner: ${{matrix.runner}}
  license:
    name: License-3rdparty
    runs-on: ubuntu-24.04
    env:
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4 # v1.11.0
        with:
          cache: false
      - uses: mozilla-actions/sccache-action@65101d47ea8028ed0c98a1cdea8dd9182e9b5133 #v0.0.8
      - run: cargo install dd-rust-license-tool
      - run: dd-rust-license-tool check
