name: Release Datadog Serverless Compat

on: workflow_dispatch

permissions: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-24.04, windows-2022]
    uses: ./.github/workflows/build-datadog-serverless-compat.yml
    with:
      runner: ${{matrix.runner}}
  release:
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # 4.3.0
        with:
          path: target/bin
      - run: |
          chmod +x target/bin/linux-amd64/datadog-serverless-compat
          chmod +x target/bin/windows-amd64/datadog-serverless-compat.exe
          upx target/bin/linux-amd64/datadog-serverless-compat --lzma
          upx target/bin/windows-amd64/datadog-serverless-compat.exe --lzma
      - run: zip -r datadog-serverless-compat.zip ./*
        working-directory: target
      - uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          draft: true
          generate_release_notes: true
          files: target/datadog-serverless-compat.zip
